version: '3.1'

services:
  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: [ "--reporter.grpc.host-port=ot.alifdev.uz:14250" ]
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14271:14271"
    restart: on-failure
